# Generated by Django 3.2.12 on 2023-04-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField()),
                ('parsed_content', models.TextField()),
                ('summarized_content', models.TextField(null=True)),
                ('source', models.TextField()),
            ],
        ),
    ]
