# Generated by Django 3.2.12 on 2023-04-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
